// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/solutions": {
    params: {};
  };
  "/solutions/:layer": {
    params: {
      "layer": string;
    };
  };
  "/products/:productId": {
    params: {
      "productId": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about" | "/contact" | "/privacy" | "/terms" | "/solutions" | "/solutions/:layer" | "/products/:productId";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/privacy.jsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/terms.jsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/solutions.jsx": {
    id: "routes/solutions";
    page: "/solutions";
  };
  "routes/solutions.layer.jsx": {
    id: "routes/solutions.layer";
    page: "/solutions/:layer";
  };
  "routes/product.jsx": {
    id: "routes/product";
    page: "/products/:productId";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "routes/home": typeof import("./src/routes/home.jsx");
  "routes/about": typeof import("./src/routes/about.jsx");
  "routes/contact": typeof import("./src/routes/contact.jsx");
  "routes/privacy": typeof import("./src/routes/privacy.jsx");
  "routes/terms": typeof import("./src/routes/terms.jsx");
  "routes/solutions": typeof import("./src/routes/solutions.jsx");
  "routes/solutions.layer": typeof import("./src/routes/solutions.layer.jsx");
  "routes/product": typeof import("./src/routes/product.jsx");
};